### ISSUE TITLE
Project proposal

### ISSUE THREAD

**Issue by jessealaney** [jessealaney/NA_Passerine_Biodiversity_Dimensionality#1]

**Comment by Angelika-Kurthen** [comment]
Hi Jesse, 

Thank you for your awesome presentation! I think you did an awesome job communicating your research and your goals. I thought your slides were really well organized. The diagramming of your analyses, along with the bullet point lists of what you plan on doing on each slide made it really easy to get an idea of what you were doing.

**Comment by Juniper41** [comment]
Your research goals were clear and concise. Your project seems very robust! I think the goal of breaking it up a bit will definitely help you out in the long run.

**Comment by McLeodMJ** [comment]
Hi Jesse!
You did a great job of describing the conceptual baseline of your project and explaining dimensionality. I think automating your work is a great goal that I'm sure we all need to work on as well (I know I can).

**Comment by zechmeunier** [comment]
Your project sounds like a whole new dissertation! I think the end product will be fascinating, especially given the continental scale. Are you planning to include any anthropogenic drivers like land use/cover type in your environmental matrices?

**Comment by jessealaney** [comment]
> Your project sounds like a whole new dissertation! I think the end product will be fascinating, especially given the continental scale. Are you planning to include any anthropogenic drivers like land use/cover type in your environmental matrices?

Thanks Zech! Ha! No, just the first chapter to my dissertation :)

I'm currently not including anthropogenic drivers, as my hypotheses are mainly focused on topographic variables, elevation, and climate. Also there are some time averaging issues assumptions with these course scale species range data I'm currently using and more recent anthropogenic metrics might now be as appropriate (?). However, if I bring in finer scale eBird data those kinds of metrics may indeed be something to consider. I'd love to chat more about it!

**Comment by breshears-logan** [comment]
And I thought my project was going to have a large and complex data set! It will be interesting to see the outcome of bringing in the eBird data. And thanks for providing an explanation for dimensionality early on, that was helpful.
